---
id: Rampage
name: Rampage
full: Rampage application server library
description: PHP 5 application framework for Horde
list: dev
type: library
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: true
    role: lead
version:
  release: 1.0.0beta1
  api: 1.0.0
state:
  release: beta
  api: beta
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
